package com.mmt.guitarlab.config

enum class FlavorType(val flavorName: String) {
    STANDARD("standard"),
    TABS("tabs");

    val isTabs: Boolean get() = this == TABS
    val isStandard: Boolean get() = this == STANDARD
}

object AppFlavorConfig {
    private var overrideFlavor: FlavorType? = null

    /**
     * Optional programmatic override (e.g. for testing / debug switcher).
     */
    fun setOverrideFlavor(flavor: FlavorType?) {
        overrideFlavor = flavor
    }

    /**
     * Currently active flavor: uses programmatic override if specified,
     * otherwise falls back to build-time Gradle productFlavor configuration.
     */
    val currentFlavor: FlavorType
        get() = overrideFlavor ?: if (isTabsFlavorBuild) FlavorType.TABS else FlavorType.STANDARD

    val isTabsFlavor: Boolean
        get() = currentFlavor == FlavorType.TABS

    val isStandardFlavor: Boolean
        get() = currentFlavor == FlavorType.STANDARD

    /**
     * Reads BuildConfig.IS_TABS_FLAVOR generated by Gradle product flavors.
     * Uses reflection for safe fallback during varied build phases.
     */
    val isTabsFlavorBuild: Boolean
        get() = try {
            val clazz = Class.forName("com.mmt.guitarlab.BuildConfig")
            val field = clazz.getField("IS_TABS_FLAVOR")
            field.getBoolean(null)
        } catch (_: Throwable) {
            false
        }

    val flavorName: String
        get() = currentFlavor.flavorName
}
